<script lang="ts">
  import type { ResultRow } from "@/background/backend";
  import classNames from "classnames";
  let _class: string = "";
  export let item: ResultRow;
  export { _class as class };
  let el: HTMLDivElement | null = null;

</script>

<div bind:this={el} data-has-snippet="1" class={classNames("fts-result pl-7", _class)}>
  <!-- Using HTML is to allow the <mark> tags generated by sqlite. This should be sanitized -->
  {@html item.snippet}
</div>
