<script lang="ts">
  import type { ResultRow } from "@/background/backend";
  import classNames from "classnames";
  import {
    getFaviconByUrl,
    cleanUrl,
    getRelativeTime,
    getFullLocalTime,
    sanitizeHtmlAllowMark,
  } from "@/common/utils";
  import { push } from "svelte-spa-router";

  export let item: ResultRow;
  export let showTime = false;
  export let showSnippets = true;
  export let selected = false;
  export let highlightClass = "bg-slate-800";
  export let groupIndex: number | undefined = undefined;

  let _class = "";
  export { _class as class };

  const handleClick = () => {
    const encodedUrl = encodeURIComponent(item.url);
    push(`/doc/${encodedUrl}`);
  };

  // Use URL only when we need to render
  $: url = item.url;
  $: urlObj = new URL(url);
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div
  data-groupIndex={groupIndex}
  class={classNames(
    "result-group p-3 -mx-2 rounded-lg",
    {
      [highlightClass]: selected,
      "bg-transparent": !selected,
    },
    _class
  )}
  on:mouseover
  on:focus
  on:click={handleClick}
>
  <a
    class={classNames("result mb-1", showTime ? "with-time" : "")}
    href={url}
    on:click|preventDefault
  >
    {#if showTime && item.last_visit}
      <div class="text-xs text-slate-500 mr-3" title={getFullLocalTime(item.last_visit)}>
        {getRelativeTime(item.last_visit)}
      </div>
    {/if}
    <div class="favicon mr-3 self-center">
      <img
        class="w-4 h-4 rounded-lg"
        src={getFaviconByUrl(url)}
        alt="favicon for {urlObj.hostname}"
      />
    </div>
    {#if item.title}
      <div class="title mr-3 text-slate-300 text-base">
        {@html sanitizeHtmlAllowMark(item.title)}
      </div>
    {/if}
    <div class="url truncate text-indigo-200">
      {cleanUrl(url)}
    </div>
  </a>

  {#if showSnippets && item.snippet && item.attribute !== "title" && item.attribute !== "url"}
    <div data-has-snippet="1" class="pl-7 truncate">
      <!-- Using HTML sanitized to only allow <mark> tags generated by the DB -->
      {@html sanitizeHtmlAllowMark(item.snippet)}
    </div>
  {/if}

  <slot></slot>
</div>

<style>
  .result:not(.with-time) {
    display: grid;
    grid-template-columns: auto auto minmax(0, 1fr);
    grid-template-rows: auto;
    align-items: baseline;
  }

  .result.with-time {
    display: grid;
    grid-template-columns: auto auto auto minmax(0, 1fr);
    grid-template-rows: auto;
    align-items: baseline;
  }
</style>
